spring:
  profiles:
    active: dev
  session:
    store-type: redis
  jmx:
    default-domain: iptv

  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    template-loader-path: classpath:/templates


swagger:
  enable: true
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true
    use-generated-keys: true